CREATE DATABASE contact_db;

USE contact_db;

CREATE TABLE contacts(
id INT AUTO_INCREMENT PRIMARY KEY,
nama VARCHAR(100) NOT NULL,
pertayaan TEXT NOT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

